export { default as ModalComponent } from './modal/modal.component';
export { default as AlertModalComponent } from './alert-modal/alert-modal.component';
export { default as ErrorMessageComponent } from './error-message/error-message.component';
export { default as ProgressComponent } from './progress/progress.component';
export { default as InfoLabelComponent } from './info-label/info-label.component';
export { default as BadgeComponent } from './badge/badge.component';
export { default as PaginationComponent } from './pagination/pagination.component';
export { default as AvatarComponent } from './avatar/avatar.component';
export { default as NavTabComponent } from './nav-tab/nav-tab.component';
export { default as BackButtonComponent } from './back-button/back-button.component';
export * from './inputs';
export * from './buttons';
export * from './registrations';
